const { ethers } = require("hardhat");

// Mint the on-chain NFT (bonus): metadata/image are generated by the
// contract itself, with no IPFS dependency.
//   npx hardhat run mint/scripts/mint-onchain.js --network bsctest

async function main() {
  const { ONCHAIN_NFT_CONTRACT_ADDRESS } = process.env;
  if (!ONCHAIN_NFT_CONTRACT_ADDRESS) {
    throw new Error("ONCHAIN_NFT_CONTRACT_ADDRESS not set in .env");
  }

  const [minter] = await ethers.getSigners();
  console.log(`Minting on-chain NFT with ${minter.address}`);

  const nft = await ethers.getContractAt("Jaehwkim42ArtOnChain", ONCHAIN_NFT_CONTRACT_ADDRESS);

  // The on-chain version needs no URI - the contract builds SVG + JSON itself
  const tx = await nft.safeMint(minter.address);
  const receipt = await tx.wait();
  console.log(`Mint tx: ${receipt.hash}`);

  const transferEvent = receipt.logs.find(
    (log) => log.fragment && log.fragment.name === "Transfer"
  );
  const tokenId = transferEvent ? transferEvent.args[2] : (await nft.totalSupply()) - 1n;
  console.log(`Token ID: ${tokenId}`);

  // Verify ownership (mandatory requirement)
  console.log(`ownerOf(${tokenId}): ${await nft.ownerOf(tokenId)}`);

  // Inspect the metadata generated fully on-chain (base64 data URI)
  const uri = await nft.tokenURI(tokenId);
  console.log(`tokenURI length: ${uri.length} chars (fully on-chain)`);
  console.log(`tokenURI (preview): ${uri.slice(0, 80)}...`);

  console.log("\nOn-chain minting complete!");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
